print("AOA")
print("My name is Mursaleen")
print("I am 17 years old")
print("I studied at diviosional public school and college")
print("I lives in Faidsalabad")
print("I want to become an AI enginner")
print("I take part in Genrative AI")
print("We have class on sunday")
print("SO me and my frends joined the class on sunday")
print("Thank you")